const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const MARKER = "companion-pods-deployment-target";
const DEFAULT_DEPLOYMENT_TARGET = "16.0";

/**
 * Xcode 26+ rejects CocoaPods whose podspec declares an
 * `IPHONEOS_DEPLOYMENT_TARGET` below iOS 15.0 as a hard build error. A handful
 * of transitive pods still ship low targets (SDWebImage 9.0, Sentry 11.0,
 * ReachabilitySwift 12.0, RNCAsyncStorage 13.4, ...). `expo-build-properties`
 * `ios.deploymentTarget` only raises the *app* target — it does not touch the
 * pod targets — so this plugin injects a Podfile `post_install` loop that
 * raises every pod build configuration to the minimum.
 *
 * The floor is 16.0 (not just the Xcode-26 minimum of 15.0) because
 * expo-router's Link Preview native code (`LinkPreviewNativeActionView.swift`)
 * calls `UIAction.subtitle`, an iOS 16+ API used without an `@available` guard,
 * which fails to compile against any target below 16.0.
 *
 * `ios/` is CNG-regenerated by `expo prebuild`, so this must live as a config
 * plugin rather than a hand edit to `ios/Podfile`.
 *
 * The insertion is idempotent (guarded by MARKER) so repeated prebuilds do not
 * stack duplicate loops.
 */
module.exports = function withIosPodsDeploymentTarget(
  config,
  { deploymentTarget = DEFAULT_DEPLOYMENT_TARGET } = {}
) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      let contents = fs.readFileSync(podfilePath, "utf8");

      if (contents.includes(MARKER)) {
        return cfg; // already injected — keep idempotent across prebuilds
      }

      const anchor = "post_install do |installer|\n";
      const anchorIdx = contents.indexOf(anchor);
      if (anchorIdx === -1) {
        throw new Error(
          "[withIosPodsDeploymentTarget] Could not find 'post_install do |installer|' in the generated Podfile."
        );
      }

      const snippet =
        `    # ${MARKER}: Xcode 26+ requires pod deployment targets >= iOS 15.0\n` +
        `    installer.pods_project.targets.each do |pods_deployment_target_target|\n` +
        `      pods_deployment_target_target.build_configurations.each do |pods_deployment_target_config|\n` +
        `        current_target = pods_deployment_target_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']\n` +
        `        if current_target.nil? || current_target.to_f < ${deploymentTarget}\n` +
        `          pods_deployment_target_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${deploymentTarget}'\n` +
        `        end\n` +
        `      end\n` +
        `    end\n`;

      const insertAt = anchorIdx + anchor.length;
      contents = contents.slice(0, insertAt) + snippet + contents.slice(insertAt);
      fs.writeFileSync(podfilePath, contents);

      return cfg;
    },
  ]);
};
