const {
  withDangerousMod,
  withInfoPlist,
  withXcodeProject,
  IOSConfig,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const MARKER = "companion-scene-lifecycle";
const SCENE_DELEGATE_FILE = "SceneDelegate.swift";

/**
 * Apps built with the iOS 27 SDK (Xcode 27) assert at launch unless they adopt
 * the UIScene life cycle ("UIScene life cycle is required for apps built with
 * this SDK"). Expo only ships a scene delegate from SDK 56 (`ExpoAppSceneDelegate`;
 * `expo-build-properties` `ios.enableSceneSupport` from 57.0.23), so on SDK 55
 * this plugin backports the same shape:
 *
 * 1. Info.plist gets a `UIApplicationSceneManifest` that NAMES a delegate class.
 *    A manifest without `UISceneDelegateClassName` opts into scenes but leaves
 *    nothing to create the window — the app launches to a blank screen.
 * 2. `SceneDelegate.swift` creates the `UIWindow` from the connecting scene,
 *    starts React Native into it with the AppDelegate's factory, and forwards
 *    lifecycle / URL / user-activity events to the AppDelegate (which already
 *    fans out to Expo subscribers and `RCTLinkingManager`).
 * 3. `AppDelegate.swift` stops creating its own window and starting React
 *    Native — the scene delegate owns that now.
 *
 * `ios/` is CNG-regenerated by `expo prebuild`, so this lives as a config
 * plugin. Remove it when upgrading to an Expo SDK whose template adopts the
 * scene life cycle (SDK 58+) or that offers `ios.enableSceneSupport`.
 */

const SCENE_DELEGATE_SOURCE = `// ${MARKER}: generated by plugins/withIosSceneLifecycle.js — do not edit by hand.
internal import Expo
import React
import UIKit

@objc(SceneDelegate)
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else { return }
    guard let appDelegate, let factory = appDelegate.reactNativeFactory else {
      fatalError("SceneDelegate: AppDelegate did not create its React Native factory in didFinishLaunching.")
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    // Mirror onto the app delegate so code reading \`UIApplication.shared.delegate?.window\` keeps working.
    appDelegate.window = window

    // Under scenes, cold-start URLs arrive in connectionOptions, not launch options.
    // React Native's Linking.getInitialURL() reads launch options, so rebuild them.
    let browsingWebActivity = connectionOptions.userActivities.first {
      $0.activityType == NSUserActivityTypeBrowsingWeb
    }
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: Self.launchOptions(
        url: connectionOptions.urlContexts.first?.url,
        userActivity: browsingWebActivity
      )
    )

    connectionOptions.urlContexts.forEach { context in
      _ = appDelegate.application(
        UIApplication.shared, open: context.url, options: Self.openURLOptions(from: context.options))
    }
    connectionOptions.userActivities.forEach { activity in
      _ = appDelegate.application(UIApplication.shared, continue: activity) { _ in }
    }
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    window = nil
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    URLContexts.forEach { context in
      _ = appDelegate?.application(
        UIApplication.shared, open: context.url, options: Self.openURLOptions(from: context.options))
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = appDelegate?.application(UIApplication.shared, continue: userActivity) { _ in }
  }

  private static func launchOptions(
    url: URL?,
    userActivity: NSUserActivity?
  ) -> [UIApplication.LaunchOptionsKey: Any]? {
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = [:]
    if let url {
      launchOptions[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey")] = url
    }
    if let userActivity {
      launchOptions[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey")] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": userActivity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": userActivity,
      ]
    }
    return launchOptions.isEmpty ? nil : launchOptions
  }

  private static func openURLOptions(
    from sceneOptions: UIScene.OpenURLOptions
  ) -> [UIApplication.OpenURLOptionsKey: Any] {
    var options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    if let sourceApplication = sceneOptions.sourceApplication {
      options[.sourceApplication] = sourceApplication
    }
    if let annotation = sceneOptions.annotation {
      options[.annotation] = annotation
    }
    options[.openInPlace] = sceneOptions.openInPlace
    return options
  }
}
`;

// The template's window-creation + startReactNative block inside
// application(_:didFinishLaunchingWithOptions:).
const APP_DELEGATE_WINDOW_BLOCK =
  /#if os\(iOS\) \|\| os\(tvOS\)\s*\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\s*\n\s*factory\.startReactNative\([\s\S]*?\)\s*\n#endif\n/;

function withSceneManifest(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: "Default Configuration",
            UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate",
          },
        ],
      },
    };
    return cfg;
  });
}

function withSceneDelegateSources(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const projectName = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
      const appDir = path.join(cfg.modRequest.platformProjectRoot, projectName);

      fs.writeFileSync(path.join(appDir, SCENE_DELEGATE_FILE), SCENE_DELEGATE_SOURCE);

      const appDelegatePath = path.join(appDir, "AppDelegate.swift");
      let appDelegate = fs.readFileSync(appDelegatePath, "utf8");
      if (!appDelegate.includes(MARKER)) {
        if (!APP_DELEGATE_WINDOW_BLOCK.test(appDelegate)) {
          throw new Error(
            "[withIosSceneLifecycle] Could not find the window/startReactNative block in AppDelegate.swift. " +
              "The Expo template changed — re-check whether this plugin is still needed."
          );
        }
        appDelegate = appDelegate.replace(
          APP_DELEGATE_WINDOW_BLOCK,
          `    // ${MARKER}: the window is created and React Native is started by SceneDelegate\n` +
            `    // under the scene-based life cycle (required by the iOS 27 SDK).\n`
        );
        fs.writeFileSync(appDelegatePath, appDelegate);
      }
      return cfg;
    },
  ]);
}

function withSceneDelegateInProject(config) {
  return withXcodeProject(config, (cfg) => {
    const projectName = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
    const filePath = `${projectName}/${SCENE_DELEGATE_FILE}`;
    if (!cfg.modResults.hasFile(filePath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: filePath,
        groupName: projectName,
        project: cfg.modResults,
      });
    }
    return cfg;
  });
}

module.exports = function withIosSceneLifecycle(config) {
  config = withSceneManifest(config);
  config = withSceneDelegateSources(config);
  config = withSceneDelegateInProject(config);
  return config;
};
