const { withProjectBuildGradle } = require("expo/config-plugins");

const MARKER = "companion-kotlin-jvmtarget";
const DEFAULT_JVM_TARGET = "17";

/**
 * Forces a consistent Kotlin `jvmTarget` across every Android subproject.
 *
 * A handful of third-party Expo modules (notably
 * `@mykin-ai/expo-audio-stream`) only pin their Kotlin `jvmTarget` when the
 * Android Gradle Plugin is < 8:
 *
 *   if (agpVersion.tokenize('.')[0].toInteger() < 8) {
 *     kotlinOptions { jvmTarget = JavaVersion.VERSION_11.majorVersion }
 *   }
 *
 * Under AGP 8+ (this project) that block is skipped, so the module's Kotlin
 * compile task inherits the running JDK's default (21 on JDK 21) while its
 * Java compile task stays at 17. Gradle then fails the build with:
 *
 *   > Inconsistent JVM-target compatibility detected for tasks
 *   > 'compileDebugJavaWithJavac' (17) and 'compileDebugKotlin' (21).
 *
 * Pinning every subproject's Kotlin task to 17 matches the Java target and
 * resolves the mismatch without patching node_modules.
 *
 * `android/` is CNG-regenerated by `expo prebuild`, so this must live as a
 * config plugin rather than a hand edit to `android/build.gradle`. The
 * insertion is idempotent (guarded by MARKER) so repeated prebuilds do not
 * stack duplicate blocks.
 */
module.exports = function withAndroidKotlinJvmTarget(
  config,
  { jvmTarget = DEFAULT_JVM_TARGET } = {}
) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error("[withAndroidKotlinJvmTarget] Expected android/build.gradle to be Groovy.");
    }

    if (cfg.modResults.contents.includes(MARKER)) {
      return cfg; // already injected — keep idempotent across prebuilds
    }

    cfg.modResults.contents +=
      `\n// ${MARKER}: pin Kotlin jvmTarget so third-party modules that skip\n` +
      `// setting it under AGP 8+ don't mismatch the Java target (17 vs 21).\n` +
      `subprojects {\n` +
      `  tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {\n` +
      `    kotlinOptions {\n` +
      `      jvmTarget = "${jvmTarget}"\n` +
      `    }\n` +
      `  }\n` +
      `}\n`;

    return cfg;
  });
};
