/**
 * AI Response Schemas — Story 9-7
 *
 * Centralized Zod schemas for every `chatCompletionJSON` call site in the
 * codebase. One source of truth for "what does the AI return," consumed by:
 *
 *   - `src/lib/openai.ts` `chatCompletionJSON<T>` — validates each response
 *     before it reaches the caller. On parse failure, the call is retried
 *     once; on retry exhaustion, `captureError(_, "ai-schema-parse-failed",
 *     { feature, attempt, code })` fires and the call rejects.
 *
 *   - Future Epic 15.5 (AI schema regression tests) — replays recorded model
 *     outputs through these schemas in CI.
 *
 *   - The TypeScript layer — `z.infer<typeof X>` is the type used by every
 *     consumer. The hand-rolled interfaces in `src/types/exercise.ts` and
 *     `src/types/conversation.ts` are now re-exports of these inferred types
 *     so the type system mirrors runtime validation exactly.
 *
 * Schema rules expressed declaratively here REPLACE the four hand-rolled
 * validators (`validateMCQExercise`, `validateEchoResponse`,
 * `validateTranslationResponse`, `validateEvaluationResponse`) and the inline
 * mock-test option-filter and placement-test polymorphic-options
 * normalization. None of those manual validators remain in the codebase.
 *
 * @see docs path: this file is the contract; CLAUDE.md "AI response
 *   validation" line points here.
 */

import { z } from "zod";

/**
 * Mirrors `MAX_PRE_SANITIZE_CHARS` from `src/lib/memory.ts`. Hardcoded here
 * (rather than imported) because `memory.ts` imports this file for
 * `factExtractionSchema`, and a circular import causes the constant to be
 * `undefined` on first read in module-graph traversal — silently breaking
 * the `.max()` rule on `factSchema.content`. If the source-of-truth in
 * `memory.ts` changes, update this constant in lockstep.
 *
 * Exported as `SCHEMA_MAX_PRE_SANITIZE_CHARS` so the lockstep regression
 * test can compare both sides of the duplication, not just one (story 9-7
 * review, P8 — fixes the asymmetric assertion).
 */
export const SCHEMA_MAX_PRE_SANITIZE_CHARS = 4096;
const MAX_PRE_SANITIZE_CHARS = SCHEMA_MAX_PRE_SANITIZE_CHARS;

// ---------------------------------------------------------------------------
// Common atomic schemas — declared once, reused across feature schemas
// ---------------------------------------------------------------------------

/**
 * CEFR proficiency level. Mirrors `src/types/cefr.ts` `CEFRLevel`.
 * Hard-coded enum (not derived from `CEFR_ORDER`) because Zod's
 * `z.enum(...)` requires a literal tuple; the runtime value is identical.
 */
export const cefrLevelSchema = z.enum(["A1", "A2", "B1", "B2", "C1", "C2"]);

/**
 * MCQ option — used by listening, reading, grammar, mock-test, placement-test.
 * Required fields: `id`, `text`, `isCorrect`. `id` and `text` must be
 * non-empty strings.
 */
export const mcqOptionSchema = z.object({
  id: z.string().min(1),
  text: z.string().min(1),
  isCorrect: z.boolean(),
});

/**
 * MCQ question — exactly 4 options, exactly 1 correct, non-empty
 * explanation, unique option ids. The `superRefine` enforces the
 * "exactly 1 correct" invariant that previously required the hand-rolled
 * `validateMCQExercise` function, plus a unique-id rule (story 9-7 review,
 * P9) so duplicate ids can't cause React key warnings or scoring confusion.
 *
 * `passage` and `passageId` are optional but, when present, must be
 * non-empty (story 9-7 review, P10).
 */
export const mcqQuestionSchema = z
  .object({
    question: z.string().min(1),
    passage: z.string().min(1).optional(),
    passageId: z.string().min(1).optional(),
    options: z.array(mcqOptionSchema).length(4),
    explanation: z.string().min(1),
  })
  .superRefine((q, ctx) => {
    const correctCount = q.options.filter((o) => o.isCorrect).length;
    if (correctCount !== 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Expected exactly 1 correct option, got ${correctCount}`,
        path: ["options"],
      });
    }
    const ids = new Set(q.options.map((o) => o.id));
    if (ids.size !== q.options.length) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Option ids must be unique",
        path: ["options"],
      });
    }
  });

// ---------------------------------------------------------------------------
// Per-feature response schemas — one per `chatCompletionJSON` call site
// ---------------------------------------------------------------------------

/**
 * Listening exercise generation. Used by `useExercise` listening branch.
 * Generated by `gpt-4o` at temperature 0.4.
 */
export const listeningExerciseSchema = z.object({
  passage: z.string().min(1),
  questions: z.array(mcqQuestionSchema).min(1),
  vocabularyHighlights: z.array(z.string()).optional(),
});

/**
 * Reading exercise generation. Used by `useExercise` reading branch.
 * Generated by `gpt-4o` at temperature 0.4.
 */
export const readingExerciseSchema = z.object({
  passage: z.string().min(1),
  questions: z.array(mcqQuestionSchema).min(1),
  wordExplanations: z.record(z.string(), z.string()).optional(),
});

/**
 * Grammar exercise generation. Used by `useExercise` grammar branch.
 * Generated by `gpt-4o` at temperature 0.4.
 */
export const grammarExerciseSchema = z.object({
  questions: z.array(mcqQuestionSchema).min(1),
});

/**
 * Writing prompt generation. Used by `useExercise` writing branch (initial
 * prompt only — evaluation has its own schema). Generated by `gpt-4o` at
 * temperature 0.4.
 */
export const writingPromptGenerationSchema = z.object({
  prompt: z.string().min(1),
  context: z.string().min(1),
});

/**
 * Writing evaluation. Used by `useExercise.submitWriting`. Generated by
 * `gpt-4o` at temperature 0.3.
 *
 * Score fields are constrained to 0-100. `errors[].category` is constrained
 * to the four labels rendered by the UI. Optional fields preserve the
 * AI's freedom to omit best-effort enrichment fields without invalidating
 * the response.
 */
export const writingErrorSchema = z.object({
  original: z.string(),
  correction: z.string(),
  explanation: z.string(),
  category: z.enum(["grammar", "cohesion", "vocabulary", "register"]),
});

export const writingEvaluationSchema = z.object({
  overallScore: z.number().min(0).max(100),
  grammarScore: z.number().min(0).max(100),
  cohesionScore: z.number().min(0).max(100),
  lexicalRichnessScore: z.number().min(0).max(100),
  registerScore: z.number().min(0).max(100),
  errors: z.array(writingErrorSchema),
  suggestions: z.array(z.string()),
  rewriteSuggestion: z.string().optional(),
  tcfEstimatedScore: z.number().optional(),
  vocabularyDiversityRatio: z.number().optional(),
  connectorsUsed: z.array(z.string()).optional(),
  connectorsMissing: z.array(z.string()).optional(),
  summary: z.string().optional(),
});

/**
 * Conversation feedback. Used by `useRealtimeVoice` post-conversation
 * summary. Generated by `gpt-4o` at temperature 0.3.
 *
 * Ratings are integer 1-5 (matches the UI star renderer); other fields
 * are non-empty arrays so the home-screen "Today's recap" card cannot
 * crash on `.map()`.
 */
export const conversationFeedbackSchema = z.object({
  summary: z.string().min(1),
  strengths: z.array(z.string()),
  improvements: z.array(z.string()),
  vocabularyUsed: z.number().int().min(0),
  fluencyRating: z.number().int().min(1).max(5),
  grammarRating: z.number().int().min(1).max(5),
});

/**
 * Dictation set. Used by `useDictation`. Generated by `gpt-4o` at
 * temperature 0.8 (creative — sentence variety matters).
 */
export const dictationSentenceSchema = z.object({
  sentence: z.string().min(1),
  translation: z.string().min(1),
  difficulty: z.enum(["easy", "medium", "hard"]),
});

export const dictationSetSchema = z.object({
  sentences: z.array(dictationSentenceSchema).min(1),
});

/**
 * Echo practice generation. Used by `generateEchoExercise`. Generated by
 * `gpt-4o` at temperature 0.4.
 *
 * Replaces the hand-rolled `validateEchoResponse` (deleted by 9-7).
 * Sentence count is 3-5 — enforced by `.min(3).max(5)`.
 */
export const echoSentenceSchema = z.object({
  sentence: z.string().min(1),
  translation: z.string().min(1),
  expectedSpelling: z.string().min(1),
  difficulty: z.enum(["easy", "medium", "hard"]),
  grammarFocus: z.string().optional(),
});

export const echoGenerationSchema = z.object({
  sentences: z.array(echoSentenceSchema).min(3).max(5),
});

/**
 * Translation generation. Used by `generateTranslationExercise`. Generated
 * by `gpt-4o` at temperature 0.4.
 *
 * Replaces the hand-rolled `validateTranslationResponse` (deleted by 9-7).
 * Sentence difficulty uses `cefrLevelSchema` (not the simpler easy/medium/hard
 * triad).
 */
export const translationSentenceSchema = z.object({
  source: z.string().min(1),
  target: z.string().min(1),
  explanation: z.string().min(1),
  difficulty: cefrLevelSchema,
  grammarFocus: z.string().min(1),
});

/**
 * Translation generation sentence-count bounds. Mirror the constants in
 * `src/lib/translation-generation.ts` (`MIN_SENTENCES = 3`,
 * `MAX_SENTENCES = 10`). Hardcoded here to avoid a circular import; a
 * regression test asserts the values stay in lockstep. Story 9-7 review (P2).
 */
const TRANSLATION_MIN_SENTENCES = 3;
const TRANSLATION_MAX_SENTENCES = 10;

export const translationGenerationSchema = z.object({
  // The caller enforces `mode` from the requested CEFR level — the AI's `mode`
  // field is ignored by the consumer. Allow it through here as optional so a
  // model that includes it doesn't fail validation.
  mode: z.enum(["translation", "paraphrasing"]).optional(),
  sentences: z
    .array(translationSentenceSchema)
    .min(TRANSLATION_MIN_SENTENCES)
    .max(TRANSLATION_MAX_SENTENCES),
});

export const TRANSLATION_SENTENCE_BOUNDS = {
  min: TRANSLATION_MIN_SENTENCES,
  max: TRANSLATION_MAX_SENTENCES,
} as const;

/**
 * Translation evaluation. Used by `evaluateTranslation`. Generated by
 * `gpt-4o` at temperature 0.4.
 *
 * Replaces the hand-rolled `validateEvaluationResponse` (deleted by 9-7).
 * The hand-rolled validator silently coerced an invalid `overallScore` to
 * `-1`; the schema rejects out-of-range values, and the caller's existing
 * recompute-from-weighted-average path handles the resulting parse retry
 * (or a missing `overallScore` after a successful retry).
 *
 * `expectedTranslation` and `userTranscription` are NOT part of the AI
 * response — they're attached by the caller after parsing — so they're
 * `.optional()` on the schema.
 */
export const translationDimensionScoreSchema = z.object({
  score: z.number().min(0).max(100),
  // Reject whitespace-only feedback (e.g. `" "`) — the deleted hand-rolled
  // validator did `.trim()` length check; restored here. Story 9-7 review (P4).
  feedback: z
    .string()
    .min(1)
    .refine((s) => s.trim().length > 0, { message: "feedback must be non-blank" }),
});

export const translationEvaluationSchema = z.object({
  accuracy: translationDimensionScoreSchema,
  fluency: translationDimensionScoreSchema,
  naturalness: translationDimensionScoreSchema,
  // overallScore is nullable + optional — caller recomputes from weighted
  // dimensions if the model omits it OR returns null OR out-of-range. The
  // model is asked to provide it; we tolerate omission/null to match the
  // existing recompute behavior. Story 9-7 review (P11): added `.nullable()`
  // so a model that emits `overallScore: null` doesn't trigger retry
  // exhaustion when the recompute path would have handled it.
  overallScore: z.number().min(0).max(100).nullable().optional(),
  corrections: z.string().optional(),
  // Caller-attached metadata, not validated against the AI response.
  expectedTranslation: z.string().optional(),
  userTranscription: z.string().optional(),
});

/**
 * Memory fact extraction. Used by `extractAndStoreMemories`. Generated by
 * `gpt-4o` at temperature 0.3.
 *
 * Content cap mirrors `MAX_PRE_SANITIZE_CHARS` (4096) — the upstream guard
 * before sanitization further trims to 300 chars. Type uses the same
 * `MemoryType` union as `companion_memory.type` checks.
 */
// Memory type enum literals — mirrors `MemoryType` in `src/lib/memory.ts`.
// Hard-coded (not derived from the runtime `MEMORY_TYPES` Set) because Zod's
// `z.enum(...)` requires a literal tuple at type-check time.
export const memoryTypeSchema = z.enum([
  "personal_fact",
  "preference",
  "topic_discussed",
  "milestone",
]);

export const factSchema = z.object({
  content: z.string().min(1).max(MAX_PRE_SANITIZE_CHARS),
  type: memoryTypeSchema,
});

export const factExtractionSchema = z.object({
  facts: z.array(factSchema),
});

/**
 * Micro-drill generation. Used by `generateMicroDrill` in error-tracker.
 * Generated by `gpt-4o` at temperature 0.5.
 */
export const microDrillQuestionSchema = z.object({
  question: z.string().min(1),
  options: z.array(z.string().min(1)).min(2),
  correctIndex: z.number().int().min(0),
  explanation: z.string().min(1),
});

export const microDrillSchema = z
  .object({
    title: z.string().min(1),
    explanation: z.string().min(1),
    questions: z.array(microDrillQuestionSchema).min(1),
    tip: z.string().min(1),
  })
  .superRefine((d, ctx) => {
    for (let i = 0; i < d.questions.length; i++) {
      const q = d.questions[i];
      if (q.correctIndex >= q.options.length) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `correctIndex ${q.correctIndex} out of range for ${q.options.length} options`,
          path: ["questions", i, "correctIndex"],
        });
      }
    }
  });

/**
 * Error pattern batch extraction. Used by `extractErrorsFromCorrections`
 * (still active for non-Realtime flows: `use-echo-practice` + `use-translation`).
 * Generated by `gpt-4o` at temperature 0.2.
 *
 * NOTE: Realtime conversations post-Story-11-5 use the consolidated
 * `postConversationAnalysisSchema` below instead, which folds error
 * patterns into the same call that produces facts + feedback.
 */
export const errorPatternBatchSchema = z.object({
  patterns: z.array(
    z.object({
      original: z.string().min(1),
      corrected: z.string().min(1),
      pattern: z.string().min(1),
      category: z.enum(["grammar", "pronunciation", "vocabulary", "register"]),
    })
  ),
});

/**
 * Combined post-conversation analysis (Story 11-5 / audit P1-10).
 *
 * Used by `extractPostConversationAnalysis` in
 * `src/lib/post-conversation-analysis.ts`. Replaces the pre-11-5 3-call
 * pattern (memories + error patterns + feedback) with a single call
 * producing all three outputs in one combined JSON. Saves ~1.25¢ per
 * conversation on input cost (transcript counted once instead of 3×).
 *
 * Sub-arrays are `.default([])` so the model can return whatever it
 * produced; missing parts default to empty (preserves the pre-11-5
 * fire-and-forget semantics where any individual extraction could
 * silently no-op). `feedback` is `.optional()` so transcripts too short
 * to feedback-on return `undefined` cleanly.
 *
 * Generated by `gpt-4o` at temperature 0.3 with maxTokens 1500 (feedback
 * ~150 + facts ~500 + errorPatterns ~500 + JSON envelope = ~1200 tokens
 * output; 1500 leaves 300 headroom).
 */
/**
 * Story 11-5 review patch P6: `.max(10)` on both arrays caps the model's
 * output at 10 facts + 10 error patterns. Without this cap, a miscalibrated
 * model could return 50+ entries, kicking off 50+ concurrent
 * `generateEmbedding` calls in `persistMemories` and hitting Story 11-4's
 * shared `"ai-proxy"` rate-limit (30/60s). Documents the prompt's expected
 * "3-7 facts" upper bound at the schema layer.
 */
export const postConversationAnalysisSchema = z.object({
  facts: z.array(factSchema).max(10).default([]),
  errorPatterns: z
    .array(
      z.object({
        original: z.string().min(1),
        corrected: z.string().min(1),
        pattern: z.string().min(1),
        category: z.enum(["grammar", "pronunciation", "vocabulary", "register"]),
      })
    )
    .max(10)
    .default([]),
  feedback: conversationFeedbackSchema.optional(),
});

/**
 * Mock test section generation. Used by the mock-test screen for
 * listening + reading sections. Generated by `gpt-4o` at temperature 0.4
 * with maxTokens 4096.
 *
 * Replaces the inline `result.questions.filter(q => q.options.length === 4 && correctCount === 1)`
 * normalization at `mock-test/[testId].tsx:335-340`. The schema's
 * `mcqQuestionSchema` enforces both invariants.
 */
export const mockTestPassageSchema = z.object({
  id: z.string().min(1),
  text: z.string().min(1),
});

export const mockTestSectionSchema = z.object({
  passages: z.array(mockTestPassageSchema).optional(),
  // Ship-blocker M2: `.min(1)` — an empty section must NOT validate. Pre-fix an
  // empty `{questions: []}` passed, flipped `firstSectionReady`, and rendered a
  // playable BLANK exam (no question body, only Submit/Next). Rejecting it makes
  // the generator mark the section failed (per-section failure isolation +
  // parseRetries) instead of shipping an empty section to the user.
  questions: z.array(mcqQuestionSchema).min(1),
});

/**
 * Pronunciation sentence generation. Used by the pronunciation practice
 * screen. Generated by `gpt-4o` at temperature 0.9 (creative variety).
 */
export const pronunciationSentenceSchema = z.object({
  sentence: z.string().min(1),
  translation: z.string().min(1),
});

/**
 * Per-task TCF Expression Orale rubric. Used by the speaking mock-test screen
 * (`app/(tabs)/mock-test/speaking.tsx`). Generated by `gpt-4o` at temperature
 * 0.3 (low creativity — assessment must be reproducible; the same transcript
 * should grade similarly across calls).
 *
 * Story 9-8 (initial 4-dimension shape).
 * Story 10-6 (added 5th `sociolinguisticScore` dimension to close the
 * publisher 3-category gap per `docs/tcf-spec-source.md §6.3`:
 * Linguistique + Pragmatique + **Sociolinguistique** — adéquation à la
 * situation de communication).
 *
 * Each dimension is on the official TCF Expression Orale 0-20 scale.
 * `overallScore` is on the 0-100 display scale used elsewhere in the app
 * (= sum of the 5 dimensions × 1.0). It is `nullable + optional` because
 * the consumer recomputes deterministically when the model omits it; failing
 * the parse over a missing overall would trigger a wasted retry per the 9-7
 * contract. This mirrors the `translationEvaluationSchema.overallScore`
 * pattern (story 9-7 review P11).
 *
 * `sociolinguisticScore` is **required** (not optional) so a legacy 4-dim
 * AI response fails Zod parse and triggers Story 9-7's retry path. Making
 * it optional would silently accept the legacy shape and over-report scores
 * by skipping the 5th publisher category.
 *
 * `strengths` / `improvements` are bounded `min(1).max(5)` for the same
 * reason as `conversationFeedbackSchema` — the home-screen card cannot crash
 * on `.map()` over empty, and the layout breaks above ~5 entries.
 */
export const speakingTaskEvaluationSchema = z.object({
  pronunciationFluencyScore: z.number().min(0).max(20),
  vocabularyScore: z.number().min(0).max(20),
  grammarScore: z.number().min(0).max(20),
  interactionScore: z.number().min(0).max(20),
  // Story 10-6: 5th publisher category (Sociolinguistique — adéquation à la
  // situation de communication). Required, not optional — see schema JSDoc.
  sociolinguisticScore: z.number().min(0).max(20),
  overallScore: z.number().min(0).max(100).nullable().optional(),
  estimatedCEFR: cefrLevelSchema.optional(),
  strengths: z.array(z.string().min(1)).min(1).max(5),
  improvements: z.array(z.string().min(1)).min(1).max(5),
  // P17: cap corrections at 2000 chars so a runaway model emission cannot
  // bloat the `mock_tests.section_scores` JSONB payload (rows are read on
  // every results-screen render and on home-screen recap).
  corrections: z.string().max(2000).optional(),
});

/**
 * `report_correction` Realtime tool-call arguments. Used by `useRealtimeVoice`
 * `handleFunctionCall` to validate the model's tool invocation payload before
 * pushing the correction into the per-turn pending-corrections buffer.
 *
 * Story 11-1 — replaces the Story 9-5 / 10-7 `parseCorrections` regex bridge
 * with structured tool-call ingestion. The schema mirrors `Correction` at
 * `src/types/conversation.ts` — `category` is the same 4-literal union
 * (`"grammar" | "pronunciation" | "vocabulary" | "register"`); the three
 * string fields are non-empty.
 *
 * Validation runs via `schema.safeParse(JSON.parse(args))` inside the
 * tool-call handler. The Realtime path does NOT route through
 * `chatCompletionJSON`, so there is no Story 9-7 retry loop — on parse
 * failure the handler returns "Invalid correction shape; correction not
 * recorded." so the model can self-correct on a subsequent invocation,
 * and a Sentry breadcrumb fires with `feature: "realtime-report-correction"`
 * + the Zod issue code.
 *
 * `correctionCategorySchema` is exported separately so future surfaces
 * (the `note_error_pattern` handler's existing inline `enum: [...]`
 * literal) could consume it as a single source of truth in a future
 * hardening story.
 */
export const correctionCategorySchema = z.enum([
  "grammar",
  "pronunciation",
  "vocabulary",
  "register",
]);

/**
 * Per-field length caps protect against a runaway model spamming arbitrarily
 * large strings into `pendingToolCorrectionsRef` (and thence into
 * `conversation_messages.corrections` JSONB). The caps match the publisher's
 * expected utterance lengths for TCF Canada (single short clauses for
 * `original` / `corrected`, 1–2 sentences for `explanation`) with comfortable
 * headroom. Story 11-1 review patch P10.
 */
export const REPORT_CORRECTION_MAX_LENGTH = {
  original: 500,
  corrected: 500,
  explanation: 1000,
} as const;

export const reportCorrectionArgsSchema = z.object({
  original: z.string().min(1).max(REPORT_CORRECTION_MAX_LENGTH.original),
  corrected: z.string().min(1).max(REPORT_CORRECTION_MAX_LENGTH.corrected),
  explanation: z.string().min(1).max(REPORT_CORRECTION_MAX_LENGTH.explanation),
  category: correctionCategorySchema,
});

export type ReportCorrectionArgs = z.infer<typeof reportCorrectionArgsSchema>;

// ---------------------------------------------------------------------------
// Placement test — the highest-stakes call with the most polymorphic AI shape
// ---------------------------------------------------------------------------

/**
 * Coerce a string|boolean truth flag to boolean. AI models occasionally emit
 * `correct: "true"` (string) instead of a boolean. The deleted
 * `resolveIsCorrect` helper handled this; restored here as a private util so
 * the schema's `.transform()` preserves the same coverage. Story 9-7 review.
 */
function coerceTruthy(v: unknown): boolean | undefined {
  if (typeof v === "boolean") return v;
  if (typeof v === "string") {
    const s = v.toLowerCase().trim();
    if (s === "true") return true;
    if (s === "false") return false;
  }
  return undefined;
}

/**
 * Placement test option — the AI sometimes returns options as a record
 * `{ a: "text", b: "text" }` instead of an array, sometimes uses
 * `correct: true` instead of `isCorrect: true`, and occasionally returns
 * `correct: "true"` as a string. The `preprocess` step on
 * `placementQuestionSchema` normalizes the question shape upstream of this
 * schema, so by the time we hit `placementOptionInputSchema` the options
 * are already an array; this schema then accepts any of the truth-flag
 * field name + type variants and an `id` or `label` for text.
 *
 * The boolean fields are typed as `unknown` so a string-encoded boolean
 * (`"true"`/`"false"`) doesn't fail validation upfront — the `.transform()`
 * runs `coerceTruthy()` to normalize.
 */
const placementOptionInputSchema = z
  .object({
    id: z.union([z.string(), z.number()]).optional(),
    label: z.string().optional(),
    text: z.string().optional(),
    value: z.string().optional(),
    isCorrect: z.unknown().optional(),
    correct: z.unknown().optional(),
    is_correct: z.unknown().optional(),
  })
  .transform((o, ctx) => {
    const idRaw = o.id ?? o.label?.toLowerCase() ?? "";
    const id = typeof idRaw === "number" ? String(idRaw) : idRaw;
    const text = o.text ?? o.label ?? o.value ?? "";
    if (!id) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Option missing id/label",
      });
      return z.NEVER;
    }
    if (!text) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Option missing text/label/value",
      });
      return z.NEVER;
    }
    const isCorrect =
      coerceTruthy(o.isCorrect) ?? coerceTruthy(o.correct) ?? coerceTruthy(o.is_correct) ?? false;
    return { id, text, isCorrect };
  });

/**
 * Placement test question — `preprocess` normalizes the AI's polymorphic
 * options shape (object-vs-array, `correct_answer` field on the question
 * vs `isCorrect` on the option) before validating. Replaces the manual
 * `resolveIsCorrect` + 30-line normalization at
 * `app/onboarding/placement-test.tsx:489-518`.
 */
/**
 * Normalize a question-level `correct_answer` (or its many aliases) to a
 * lowercase, trimmed string id. Returns `""` if no field is present.
 *
 * Handles AI quirks documented across real placement-test runs (story 9-7
 * review, finding P1):
 *   - case mismatch: `correct_answer: "B"` against options keyed `a,b,c,d`
 *   - numeric index: `correct_answer: 1` (means option at index 1)
 *   - field-name variance: `answer`, `correctAnswer`, `correct`,
 *     `correctOption`, `correct_option`
 */
function resolvePlacementCorrectKey(obj: Record<string, unknown>): {
  correctId: string;
  correctIdx: number | null;
} {
  const raw =
    obj.correct_answer ??
    obj.answer ??
    obj.correctAnswer ??
    obj.correct ??
    obj.correctOption ??
    obj.correct_option;
  if (raw === undefined || raw === null) return { correctId: "", correctIdx: null };
  if (typeof raw === "number" && Number.isInteger(raw) && raw >= 0) {
    return { correctId: "", correctIdx: raw };
  }
  return { correctId: String(raw).toLowerCase().trim(), correctIdx: null };
}

export const placementQuestionSchema = z
  .preprocess(
    (q: unknown) => {
      if (!q || typeof q !== "object") return q;
      const obj = q as Record<string, unknown>;
      const rawOpts = obj.options;

      // Convert { a: "...", b: "..." } shape → array shape
      if (rawOpts && typeof rawOpts === "object" && !Array.isArray(rawOpts)) {
        const optsArray = Object.entries(rawOpts as Record<string, unknown>)
          // Treat null/undefined values as a hard error rather than coercing
          // to the literal string "null" / "undefined". Story 9-7 review (P7).
          .filter(([, val]) => val !== null && val !== undefined)
          .map(([key, val]) => {
            if (typeof val === "string") {
              return { id: key.toLowerCase(), text: val, isCorrect: false };
            }
            if (val && typeof val === "object") {
              const v = val as Record<string, unknown>;
              return {
                id: key.toLowerCase(),
                text: typeof v.text === "string" ? v.text : String(val),
                isCorrect: coerceTruthy(v.isCorrect) ?? coerceTruthy(v.correct) ?? false,
              };
            }
            return { id: key.toLowerCase(), text: String(val), isCorrect: false };
          });
        // Resolve correct from question-level field (correct_answer/answer/etc.)
        // — both the lowercased-id and numeric-index branches.
        const { correctId, correctIdx } = resolvePlacementCorrectKey(obj);
        if (correctId) {
          const target = optsArray.find((o) => o.id === correctId);
          if (target) target.isCorrect = true;
        } else if (correctIdx !== null && correctIdx < optsArray.length) {
          optsArray[correctIdx].isCorrect = true;
        }
        return { ...obj, options: optsArray };
      }

      // Already an array — filter null/non-object entries (story 9-7 review,
      // P7) and resolve correct flags through coerceTruthy to handle string-
      // boolean variants.
      if (Array.isArray(rawOpts)) {
        const cleanOpts = rawOpts.filter((o) => o && typeof o === "object");
        const hasCorrect = cleanOpts.some((o) => {
          const oo = o as Record<string, unknown>;
          return (
            coerceTruthy(oo.isCorrect) === true ||
            coerceTruthy(oo.correct) === true ||
            coerceTruthy(oo.is_correct) === true
          );
        });
        if (!hasCorrect) {
          const { correctId, correctIdx } = resolvePlacementCorrectKey(obj);
          if (correctId || correctIdx !== null) {
            const newOpts = cleanOpts.map((o, i) => {
              const oo = o as Record<string, unknown>;
              const rawId = (oo.id as string | number | undefined) ?? oo.label;
              const oid =
                typeof rawId === "string"
                  ? rawId.toLowerCase().trim()
                  : typeof rawId === "number"
                    ? String(rawId)
                    : String.fromCharCode(97 + i);
              const matchesById = correctId !== "" && oid === correctId;
              const matchesByIdx = correctIdx !== null && i === correctIdx;
              return { ...oo, isCorrect: matchesById || matchesByIdx };
            });
            return { ...obj, options: newOpts };
          }
        }
        // Even if a `correct` field is already present, normalize array entries
        // to drop null/non-object slots so the inner schema doesn't fail on
        // sparse input.
        return { ...obj, options: cleanOpts };
      }

      return q;
    },
    z.object({
      level: cefrLevelSchema,
      question: z.string().min(1),
      options: z.array(placementOptionInputSchema).length(4),
      explanation: z.string().min(1),
    })
  )
  .superRefine((q, ctx) => {
    const correctCount = q.options.filter((o) => o.isCorrect).length;
    if (correctCount !== 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Expected exactly 1 correct option, got ${correctCount}`,
        path: ["options"],
      });
    }
    // Unique-id check (story 9-7 review, P9). Duplicate ids cause React-key
    // warnings and scoring confusion downstream.
    const ids = new Set(q.options.map((o) => o.id));
    if (ids.size !== q.options.length) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Option ids must be unique",
        path: ["options"],
      });
    }
  });

/**
 * Placement test response. 15 questions, distributed A1:3, A2:3, B1:3, B2:3,
 * C1:2, C2:1. Generated by `gpt-4o` at temperature 0.5 with maxTokens 4096.
 */
export const placementTestSchema = z.object({
  // Target is 15 (A1:3 / A2:3 / B1:3 / B2:3 / C1:2 / C2:1 per
  // PLACEMENT_LEVEL_RANGES). Ship-blocker M4: relaxed from a strict
  // `.length(15)` to a ±3 tolerance band. gpt-4o occasionally returns 14 or 16;
  // the strict length rejected the ENTIRE response, burning up to ~9 gpt-4o
  // calls (outer MAX_RETRIES=2 × inner parseRetries=2) before the error screen
  // on the critical onboarding path. The index-based scoring
  // (`levelForQuestion` clamps out-of-range indices to C2; mastery uses `>=`
  // against fixed per-level totals) tolerates small count deviations
  // gracefully. A count outside the band is clearly malformed → still retries.
  questions: z.array(placementQuestionSchema).min(12).max(18),
});

// ---------------------------------------------------------------------------
// Inferred type re-exports — the type system mirrors runtime validation
// ---------------------------------------------------------------------------

export type CEFRLevelInferred = z.infer<typeof cefrLevelSchema>;
export type MCQOptionInferred = z.infer<typeof mcqOptionSchema>;
export type MCQQuestionInferred = z.infer<typeof mcqQuestionSchema>;
export type ListeningExerciseResponse = z.infer<typeof listeningExerciseSchema>;
export type ReadingExerciseResponse = z.infer<typeof readingExerciseSchema>;
export type GrammarExerciseResponse = z.infer<typeof grammarExerciseSchema>;
export type WritingPromptGenerationResponse = z.infer<typeof writingPromptGenerationSchema>;
export type WritingEvaluationInferred = z.infer<typeof writingEvaluationSchema>;
export type WritingErrorInferred = z.infer<typeof writingErrorSchema>;
export type ConversationFeedbackInferred = z.infer<typeof conversationFeedbackSchema>;
export type PostConversationAnalysisInferred = z.infer<typeof postConversationAnalysisSchema>;
export type DictationSentenceInferred = z.infer<typeof dictationSentenceSchema>;
export type DictationSetInferred = z.infer<typeof dictationSetSchema>;
export type EchoSentenceInferred = z.infer<typeof echoSentenceSchema>;
export type EchoGenerationResponse = z.infer<typeof echoGenerationSchema>;
export type TranslationSentenceInferred = z.infer<typeof translationSentenceSchema>;
export type TranslationGenerationResponse = z.infer<typeof translationGenerationSchema>;
export type TranslationEvaluationInferred = z.infer<typeof translationEvaluationSchema>;
export type FactExtractionResponse = z.infer<typeof factExtractionSchema>;
export type MicroDrillInferred = z.infer<typeof microDrillSchema>;
export type ErrorPatternBatchInferred = z.infer<typeof errorPatternBatchSchema>;
export type MockTestSectionResponse = z.infer<typeof mockTestSectionSchema>;
export type PronunciationSentenceInferred = z.infer<typeof pronunciationSentenceSchema>;
export type SpeakingTaskEvaluation = z.infer<typeof speakingTaskEvaluationSchema>;
export type CorrectionCategoryInferred = z.infer<typeof correctionCategorySchema>;
export type PlacementQuestionInferred = z.infer<typeof placementQuestionSchema>;
export type PlacementTestResponse = z.infer<typeof placementTestSchema>;
