/**
 * AI Response Schemas — Story 9-7
 *
 * Centralized Zod schemas for every `chatCompletionJSON` call site in the
 * codebase. One source of truth for "what does the AI return," consumed by:
 *
 *   - `src/lib/openai.ts` `chatCompletionJSON<T>` — validates each response
 *     before it reaches the caller. On parse failure, the call is retried
 *     once; on retry exhaustion, `captureError(_, "ai-schema-parse-failed",
 *     { feature, attempt, code })` fires and the call rejects.
 *
 *   - Future Epic 15.5 (AI schema regression tests) — replays recorded model
 *     outputs through these schemas in CI.
 *
 *   - The TypeScript layer — `z.infer<typeof X>` is the type used by every
 *     consumer. The hand-rolled interfaces in `src/types/exercise.ts` and
 *     `src/types/conversation.ts` are now re-exports of these inferred types
 *     so the type system mirrors runtime validation exactly.
 *
 * Schema rules expressed declaratively here REPLACE the four hand-rolled
 * validators (`validateMCQExercise`, `validateEchoResponse`,
 * `validateTranslationResponse`, `validateEvaluationResponse`) and the inline
 * mock-test option-filter and placement-test polymorphic-options
 * normalization. None of those manual validators remain in the codebase.
 *
 * @see docs path: this file is the contract; CLAUDE.md "AI response
 *   validation" line points here.
 */

import { z } from "zod";

/**
 * Mirrors `MAX_PRE_SANITIZE_CHARS` from `src/lib/memory.ts`. Hardcoded here
 * (rather than imported) because `memory.ts` imports this file for
 * `factExtractionSchema`, and a circular import causes the constant to be
 * `undefined` on first read in module-graph traversal — silently breaking
 * the `.max()` rule on `factSchema.content`. If the source-of-truth in
 * `memory.ts` changes, update this constant in lockstep (the two values
 * are asserted equal in `ai-responses.test.ts`).
 */
const MAX_PRE_SANITIZE_CHARS = 4096;

// ---------------------------------------------------------------------------
// Common atomic schemas — declared once, reused across feature schemas
// ---------------------------------------------------------------------------

/**
 * CEFR proficiency level. Mirrors `src/types/cefr.ts` `CEFRLevel`.
 * Hard-coded enum (not derived from `CEFR_ORDER`) because Zod's
 * `z.enum(...)` requires a literal tuple; the runtime value is identical.
 */
export const cefrLevelSchema = z.enum(["A1", "A2", "B1", "B2", "C1", "C2"]);

/**
 * MCQ option — used by listening, reading, grammar, mock-test, placement-test.
 * Required fields: `id`, `text`, `isCorrect`. `id` and `text` must be
 * non-empty strings.
 */
export const mcqOptionSchema = z.object({
  id: z.string().min(1),
  text: z.string().min(1),
  isCorrect: z.boolean(),
});

/**
 * MCQ question — exactly 4 options, exactly 1 correct, non-empty
 * explanation. The `superRefine` enforces the "exactly 1 correct" invariant
 * that previously required the hand-rolled `validateMCQExercise` function.
 */
export const mcqQuestionSchema = z
  .object({
    question: z.string().min(1),
    passage: z.string().optional(),
    passageId: z.string().optional(),
    options: z.array(mcqOptionSchema).length(4),
    explanation: z.string().min(1),
  })
  .superRefine((q, ctx) => {
    const correctCount = q.options.filter((o) => o.isCorrect).length;
    if (correctCount !== 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Expected exactly 1 correct option, got ${correctCount}`,
        path: ["options"],
      });
    }
  });

// ---------------------------------------------------------------------------
// Per-feature response schemas — one per `chatCompletionJSON` call site
// ---------------------------------------------------------------------------

/**
 * Listening exercise generation. Used by `useExercise` listening branch.
 * Generated by `gpt-4o` at temperature 0.4.
 */
export const listeningExerciseSchema = z.object({
  passage: z.string().min(1),
  questions: z.array(mcqQuestionSchema).min(1),
  vocabularyHighlights: z.array(z.string()).optional(),
});

/**
 * Reading exercise generation. Used by `useExercise` reading branch.
 * Generated by `gpt-4o` at temperature 0.4.
 */
export const readingExerciseSchema = z.object({
  passage: z.string().min(1),
  questions: z.array(mcqQuestionSchema).min(1),
  wordExplanations: z.record(z.string(), z.string()).optional(),
});

/**
 * Grammar exercise generation. Used by `useExercise` grammar branch.
 * Generated by `gpt-4o` at temperature 0.4.
 */
export const grammarExerciseSchema = z.object({
  questions: z.array(mcqQuestionSchema).min(1),
});

/**
 * Writing prompt generation. Used by `useExercise` writing branch (initial
 * prompt only — evaluation has its own schema). Generated by `gpt-4o` at
 * temperature 0.4.
 */
export const writingPromptGenerationSchema = z.object({
  prompt: z.string().min(1),
  context: z.string().min(1),
});

/**
 * Writing evaluation. Used by `useExercise.submitWriting`. Generated by
 * `gpt-4o` at temperature 0.3.
 *
 * Score fields are constrained to 0-100. `errors[].category` is constrained
 * to the four labels rendered by the UI. Optional fields preserve the
 * AI's freedom to omit best-effort enrichment fields without invalidating
 * the response.
 */
export const writingErrorSchema = z.object({
  original: z.string(),
  correction: z.string(),
  explanation: z.string(),
  category: z.enum(["grammar", "cohesion", "vocabulary", "register"]),
});

export const writingEvaluationSchema = z.object({
  overallScore: z.number().min(0).max(100),
  grammarScore: z.number().min(0).max(100),
  cohesionScore: z.number().min(0).max(100),
  lexicalRichnessScore: z.number().min(0).max(100),
  registerScore: z.number().min(0).max(100),
  errors: z.array(writingErrorSchema),
  suggestions: z.array(z.string()),
  rewriteSuggestion: z.string().optional(),
  tcfEstimatedScore: z.number().optional(),
  vocabularyDiversityRatio: z.number().optional(),
  connectorsUsed: z.array(z.string()).optional(),
  connectorsMissing: z.array(z.string()).optional(),
  summary: z.string().optional(),
});

/**
 * Conversation feedback. Used by `useRealtimeVoice` post-conversation
 * summary. Generated by `gpt-4o` at temperature 0.3.
 *
 * Ratings are integer 1-5 (matches the UI star renderer); other fields
 * are non-empty arrays so the home-screen "Today's recap" card cannot
 * crash on `.map()`.
 */
export const conversationFeedbackSchema = z.object({
  summary: z.string().min(1),
  strengths: z.array(z.string()),
  improvements: z.array(z.string()),
  vocabularyUsed: z.number().int().min(0),
  fluencyRating: z.number().int().min(1).max(5),
  grammarRating: z.number().int().min(1).max(5),
});

/**
 * Dictation set. Used by `useDictation`. Generated by `gpt-4o` at
 * temperature 0.8 (creative — sentence variety matters).
 */
export const dictationSentenceSchema = z.object({
  sentence: z.string().min(1),
  translation: z.string().min(1),
  difficulty: z.enum(["easy", "medium", "hard"]),
});

export const dictationSetSchema = z.object({
  sentences: z.array(dictationSentenceSchema).min(1),
});

/**
 * Echo practice generation. Used by `generateEchoExercise`. Generated by
 * `gpt-4o` at temperature 0.4.
 *
 * Replaces the hand-rolled `validateEchoResponse` (deleted by 9-7).
 * Sentence count is 3-5 — enforced by `.min(3).max(5)`.
 */
export const echoSentenceSchema = z.object({
  sentence: z.string().min(1),
  translation: z.string().min(1),
  expectedSpelling: z.string().min(1),
  difficulty: z.enum(["easy", "medium", "hard"]),
  grammarFocus: z.string().optional(),
});

export const echoGenerationSchema = z.object({
  sentences: z.array(echoSentenceSchema).min(3).max(5),
});

/**
 * Translation generation. Used by `generateTranslationExercise`. Generated
 * by `gpt-4o` at temperature 0.4.
 *
 * Replaces the hand-rolled `validateTranslationResponse` (deleted by 9-7).
 * Sentence difficulty uses `cefrLevelSchema` (not the simpler easy/medium/hard
 * triad).
 */
export const translationSentenceSchema = z.object({
  source: z.string().min(1),
  target: z.string().min(1),
  explanation: z.string().min(1),
  difficulty: cefrLevelSchema,
  grammarFocus: z.string().min(1),
});

export const translationGenerationSchema = z.object({
  // The caller enforces `mode` from the requested CEFR level — the AI's `mode`
  // field is ignored by the consumer. Allow it through here as optional so a
  // model that includes it doesn't fail validation.
  mode: z.enum(["translation", "paraphrasing"]).optional(),
  sentences: z.array(translationSentenceSchema).min(1),
});

/**
 * Translation evaluation. Used by `evaluateTranslation`. Generated by
 * `gpt-4o` at temperature 0.4.
 *
 * Replaces the hand-rolled `validateEvaluationResponse` (deleted by 9-7).
 * The hand-rolled validator silently coerced an invalid `overallScore` to
 * `-1`; the schema rejects out-of-range values, and the caller's existing
 * recompute-from-weighted-average path handles the resulting parse retry
 * (or a missing `overallScore` after a successful retry).
 *
 * `expectedTranslation` and `userTranscription` are NOT part of the AI
 * response — they're attached by the caller after parsing — so they're
 * `.optional()` on the schema.
 */
export const translationDimensionScoreSchema = z.object({
  score: z.number().min(0).max(100),
  feedback: z.string().min(1),
});

export const translationEvaluationSchema = z.object({
  accuracy: translationDimensionScoreSchema,
  fluency: translationDimensionScoreSchema,
  naturalness: translationDimensionScoreSchema,
  // overallScore is optional — caller recomputes from weighted dimensions if
  // the model omits it or returns out-of-range. The model is asked to provide
  // it; we tolerate omission to match the existing recompute behavior.
  overallScore: z.number().min(0).max(100).optional(),
  corrections: z.string().optional(),
  // Caller-attached metadata, not validated against the AI response.
  expectedTranslation: z.string().optional(),
  userTranscription: z.string().optional(),
});

/**
 * Memory fact extraction. Used by `extractAndStoreMemories`. Generated by
 * `gpt-4o` at temperature 0.3.
 *
 * Content cap mirrors `MAX_PRE_SANITIZE_CHARS` (4096) — the upstream guard
 * before sanitization further trims to 300 chars. Type uses the same
 * `MemoryType` union as `companion_memory.type` checks.
 */
// Memory type enum literals — mirrors `MemoryType` in `src/lib/memory.ts`.
// Hard-coded (not derived from the runtime `MEMORY_TYPES` Set) because Zod's
// `z.enum(...)` requires a literal tuple at type-check time.
export const memoryTypeSchema = z.enum([
  "personal_fact",
  "preference",
  "topic_discussed",
  "milestone",
]);

export const factSchema = z.object({
  content: z.string().min(1).max(MAX_PRE_SANITIZE_CHARS),
  type: memoryTypeSchema,
});

export const factExtractionSchema = z.object({
  facts: z.array(factSchema),
});

/**
 * Micro-drill generation. Used by `generateMicroDrill` in error-tracker.
 * Generated by `gpt-4o` at temperature 0.5.
 */
export const microDrillQuestionSchema = z.object({
  question: z.string().min(1),
  options: z.array(z.string().min(1)).min(2),
  correctIndex: z.number().int().min(0),
  explanation: z.string().min(1),
});

export const microDrillSchema = z
  .object({
    title: z.string().min(1),
    explanation: z.string().min(1),
    questions: z.array(microDrillQuestionSchema).min(1),
    tip: z.string().min(1),
  })
  .superRefine((d, ctx) => {
    for (let i = 0; i < d.questions.length; i++) {
      const q = d.questions[i];
      if (q.correctIndex >= q.options.length) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `correctIndex ${q.correctIndex} out of range for ${q.options.length} options`,
          path: ["questions", i, "correctIndex"],
        });
      }
    }
  });

/**
 * Error pattern batch extraction. Used by `extractErrorsFromCorrections`.
 * Generated by `gpt-4o` at temperature 0.2.
 */
export const errorPatternBatchSchema = z.object({
  patterns: z.array(
    z.object({
      original: z.string().min(1),
      corrected: z.string().min(1),
      pattern: z.string().min(1),
      category: z.enum(["grammar", "pronunciation", "vocabulary", "register"]),
    })
  ),
});

/**
 * Mock test section generation. Used by the mock-test screen for
 * listening + reading sections. Generated by `gpt-4o` at temperature 0.4
 * with maxTokens 4096.
 *
 * Replaces the inline `result.questions.filter(q => q.options.length === 4 && correctCount === 1)`
 * normalization at `mock-test/[testId].tsx:335-340`. The schema's
 * `mcqQuestionSchema` enforces both invariants.
 */
export const mockTestPassageSchema = z.object({
  id: z.string().min(1),
  text: z.string().min(1),
});

export const mockTestSectionSchema = z.object({
  passages: z.array(mockTestPassageSchema).optional(),
  questions: z.array(mcqQuestionSchema),
});

/**
 * Pronunciation sentence generation. Used by the pronunciation practice
 * screen. Generated by `gpt-4o` at temperature 0.9 (creative variety).
 */
export const pronunciationSentenceSchema = z.object({
  sentence: z.string().min(1),
  translation: z.string().min(1),
});

// ---------------------------------------------------------------------------
// Placement test — the highest-stakes call with the most polymorphic AI shape
// ---------------------------------------------------------------------------

/**
 * Placement test option — the AI sometimes returns options as a record
 * `{ a: "text", b: "text" }` instead of an array, sometimes uses
 * `correct: true` instead of `isCorrect: true`. The `preprocess` step on
 * `placementQuestionSchema` normalizes the question shape upstream of this
 * schema, so by the time we hit `placementOptionInputSchema` the options
 * are already an array; this schema then accepts either a `correct` or an
 * `isCorrect` flag and an `id` or `label` for text.
 */
const placementOptionInputSchema = z
  .object({
    id: z.string().optional(),
    label: z.string().optional(),
    text: z.string().optional(),
    value: z.string().optional(),
    isCorrect: z.boolean().optional(),
    correct: z.boolean().optional(),
    is_correct: z.boolean().optional(),
  })
  .transform((o, ctx) => {
    const id = o.id ?? o.label?.toLowerCase() ?? "";
    const text = o.text ?? o.label ?? o.value ?? "";
    if (!id) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Option missing id/label",
      });
      return z.NEVER;
    }
    if (!text) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Option missing text/label/value",
      });
      return z.NEVER;
    }
    return {
      id,
      text,
      isCorrect: o.isCorrect ?? o.correct ?? o.is_correct ?? false,
    };
  });

/**
 * Placement test question — `preprocess` normalizes the AI's polymorphic
 * options shape (object-vs-array, `correct_answer` field on the question
 * vs `isCorrect` on the option) before validating. Replaces the manual
 * `resolveIsCorrect` + 30-line normalization at
 * `app/onboarding/placement-test.tsx:489-518`.
 */
export const placementQuestionSchema = z
  .preprocess(
    (q: unknown) => {
      if (!q || typeof q !== "object") return q;
      const obj = q as Record<string, unknown>;
      const rawOpts = obj.options;

      // Convert { a: "...", b: "..." } shape → array shape
      if (rawOpts && typeof rawOpts === "object" && !Array.isArray(rawOpts)) {
        const optsArray = Object.entries(rawOpts as Record<string, unknown>).map(([key, val]) => {
          if (typeof val === "string") {
            return { id: key, text: val, isCorrect: false };
          }
          if (val && typeof val === "object") {
            const v = val as Record<string, unknown>;
            return {
              id: key,
              text: typeof v.text === "string" ? v.text : String(val),
              isCorrect: false,
            };
          }
          return { id: key, text: String(val), isCorrect: false };
        });
        // Resolve correct from question-level field (correct_answer / answer / etc.)
        const correctId = String(
          obj.correct_answer ??
            obj.answer ??
            obj.correctAnswer ??
            obj.correct ??
            obj.correctOption ??
            ""
        );
        if (correctId) {
          const target = optsArray.find((o) => o.id === correctId);
          if (target) target.isCorrect = true;
        }
        return { ...obj, options: optsArray };
      }

      // Already an array — if no option has isCorrect: true but the question has
      // a `correct_answer` field, propagate it to the matching option.
      if (Array.isArray(rawOpts)) {
        const hasCorrect = rawOpts.some(
          (o) => o && typeof o === "object" && (o as Record<string, unknown>).isCorrect === true
        );
        if (!hasCorrect) {
          const correctId = String(
            obj.correct_answer ??
              obj.answer ??
              obj.correctAnswer ??
              obj.correct ??
              obj.correctOption ??
              ""
          );
          if (correctId) {
            const newOpts = rawOpts.map((o, i) => {
              if (!o || typeof o !== "object") return o;
              const oo = o as Record<string, unknown>;
              const oid =
                (oo.id as string) ??
                (oo.label as string)?.toLowerCase() ??
                String.fromCharCode(97 + i);
              return { ...oo, isCorrect: oid === correctId };
            });
            return { ...obj, options: newOpts };
          }
        }
      }

      return q;
    },
    z.object({
      level: cefrLevelSchema,
      question: z.string().min(1),
      options: z.array(placementOptionInputSchema).length(4),
      explanation: z.string().min(1),
    })
  )
  .superRefine((q, ctx) => {
    const correctCount = q.options.filter((o) => o.isCorrect).length;
    if (correctCount !== 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Expected exactly 1 correct option, got ${correctCount}`,
        path: ["options"],
      });
    }
  });

/**
 * Placement test response. 15 questions, distributed A1:3, A2:3, B1:3, B2:3,
 * C1:2, C2:1. Generated by `gpt-4o` at temperature 0.5 with maxTokens 4096.
 */
export const placementTestSchema = z.object({
  questions: z.array(placementQuestionSchema).length(15),
});

// ---------------------------------------------------------------------------
// Inferred type re-exports — the type system mirrors runtime validation
// ---------------------------------------------------------------------------

export type CEFRLevelInferred = z.infer<typeof cefrLevelSchema>;
export type MCQOptionInferred = z.infer<typeof mcqOptionSchema>;
export type MCQQuestionInferred = z.infer<typeof mcqQuestionSchema>;
export type ListeningExerciseResponse = z.infer<typeof listeningExerciseSchema>;
export type ReadingExerciseResponse = z.infer<typeof readingExerciseSchema>;
export type GrammarExerciseResponse = z.infer<typeof grammarExerciseSchema>;
export type WritingPromptGenerationResponse = z.infer<typeof writingPromptGenerationSchema>;
export type WritingEvaluationInferred = z.infer<typeof writingEvaluationSchema>;
export type WritingErrorInferred = z.infer<typeof writingErrorSchema>;
export type ConversationFeedbackInferred = z.infer<typeof conversationFeedbackSchema>;
export type DictationSentenceInferred = z.infer<typeof dictationSentenceSchema>;
export type DictationSetInferred = z.infer<typeof dictationSetSchema>;
export type EchoSentenceInferred = z.infer<typeof echoSentenceSchema>;
export type EchoGenerationResponse = z.infer<typeof echoGenerationSchema>;
export type TranslationSentenceInferred = z.infer<typeof translationSentenceSchema>;
export type TranslationGenerationResponse = z.infer<typeof translationGenerationSchema>;
export type TranslationEvaluationInferred = z.infer<typeof translationEvaluationSchema>;
export type FactExtractionResponse = z.infer<typeof factExtractionSchema>;
export type MicroDrillInferred = z.infer<typeof microDrillSchema>;
export type ErrorPatternBatchInferred = z.infer<typeof errorPatternBatchSchema>;
export type MockTestSectionResponse = z.infer<typeof mockTestSectionSchema>;
export type PronunciationSentenceInferred = z.infer<typeof pronunciationSentenceSchema>;
export type PlacementQuestionInferred = z.infer<typeof placementQuestionSchema>;
export type PlacementTestResponse = z.infer<typeof placementTestSchema>;
